function [Shape_out, Camera_out] = part_assembly_opt(Image,...
    Shape_init,...
    Camera_init,...
    Para)
% This function taks an initial assembled shape and refines it to match the
% given 3D shape. The camera configuration is optimized as well

